apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sight
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: sight
        image: docker.pkg.github.com/miguelmoll/sight/sight:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
